# ==============================================================================
# Build production version of the library.
# ==============================================================================
name: Prod Build

on:
  push:
    branches:
      - main

jobs:
  NetForge:
    uses: ./.github/workflows/pack-library.yml