name: check-secrets
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
jobs:
  secret-checks:
    name: secret-checks
    runs-on: saritasa-rocks-eks
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Check secrets
        uses: saritasa-nest/saritasa-github-actions/.github/actions/secrets-checks@v3.1
        with:
          enable-trivy-check: true
          enable-gitleaks-check: true
          github-token: ${{secrets.GITHUB_TOKEN}}
          gitleaks-license: ${{secrets.GITLEAKS_LICENSE}}
          gitleaks-slack-webhook: ${{secrets.GITLEAKS_SLACK_WEBHOOK_URL}}
